name: SyncChest
version: '2.0.1'
main: cloud.nextflow.syncchest.SyncChest
api-version: 1.18
authors: [ Queryzi ]
description: A plugin that syncs a virtual chest on a MySQL database.
website: www.nextflow.cloud
commands:
  schest:
    description: "A MySQL syncable plugin"